version: '3.7'
services:
  api:
    image: thunderous-soldier:latest
    container_name: thunderous-soldier
    expose:
      - 8095
    environment:
      - VIRTUAL_HOST=octiumlabs.com
      - VIRTUAL_PORT=8095
      - LETSENCRYPT_HOST=octiumlabs.com
      - LETSENCRYPT_EMAIL=16apterson@gmail.com
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    name: nginx-proxy